# Project:   hs-rustlib
# File:      rustfmt.toml
# Purpose:   Rust formatter configuration
# Language:  TOML
#
# License:   LicenseRef-HyperSec-EULA
# Copyright: (c) 2025 HyperSec

edition = "2021"
max_width = 100
tab_spaces = 4
use_small_heuristics = "Default"
